#!/bin/bash

# =========================
# Update System
# =========================

sudo apt update -y

# =========================
# Install curl unzip wget
# =========================

sudo apt install -y curl unzip wget apt-transport-https ca-certificates gnupg lsb-release

# =========================
# Install AWS CLI
# =========================

curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"

unzip awscliv2.zip

sudo ./aws/install

aws --version

# =========================
# Install kubectl
# =========================

curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

kubectl version --client

# =========================
# Install eksctl
# =========================

curl --silent --location \
"https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" \
| tar xz -C /tmp

sudo mv /tmp/eksctl /usr/local/bin

eksctl version

eksctl create cluster \
--name EKS_CLUSTER \
--region ap-south-1 \
--nodegroup-name workers \
--node-type t3.medium \
--nodes 2
