#!/bin/bash

# Update system
sudo apt update -y

# Install Java 17
sudo apt install openjdk-17-jdk unzip wget -y

# Verify Java
java -version

# Install PostgreSQL
sudo apt install postgresql postgresql-contrib -y

# Start and enable PostgreSQL
sudo systemctl enable postgresql
sudo systemctl start postgresql

# Create SonarQube database and user
sudo -u postgres psql <<EOF
CREATE DATABASE sonarqube;
CREATE USER sonar WITH ENCRYPTED PASSWORD 'sonar123';
GRANT ALL PRIVILEGES ON DATABASE sonarqube TO sonar;
EOF

# Create sonar user
sudo useradd -m -d /opt/sonarqube -r -s /bin/bash sonar

# Download SonarQube
cd /tmp
wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-10.5.1.90531.zip

# Unzip
sudo unzip sonarqube-10.5.1.90531.zip -d /opt/

# Rename folder
sudo mv /opt/sonarqube-10.5.1.90531 /opt/sonarqube

# Change ownership
sudo chown -R sonar:sonar /opt/sonarqube

# Configure database
sudo bash -c 'cat >> /opt/sonarqube/sonarqube-10.5.1.90531/conf/sonar.properties <<EOF

sonar.jdbc.username=sonar
sonar.jdbc.password=sonar123
sonar.jdbc.url=jdbc:postgresql://localhost:5432/sonarqube
EOF'

# Configure Linux kernel settings
echo "vm.max_map_count=524288" | sudo tee -a /etc/sysctl.conf
echo "fs.file-max=131072" | sudo tee -a /etc/sysctl.conf

echo "sonar   -   nofile   131072" | sudo tee -a /etc/security/limits.conf
echo "sonar   -   nproc    8192" | sudo tee -a /etc/security/limits.conf

sudo sysctl -p

# Create systemd service
sudo tee /etc/systemd/system/sonarqube.service > /dev/null <<EOF
[Unit]
Description=SonarQube service
After=syslog.target network.target

[Service]
Type=forking

ExecStart=/opt/sonarqube/bin/linux-x86-64/sonar.sh start
ExecStop=/opt/sonarqube/bin/linux-x86-64/sonar.sh stop

User=sonar
Group=sonar
Restart=always
LimitNOFILE=131072
LimitNPROC=8192

[Install]
WantedBy=multi-user.target
EOF

# Reload systemd
sudo systemctl daemon-reload

# Enable SonarQube
sudo systemctl enable sonarqube

# Start SonarQube
sudo systemctl start sonarqube

# Show status
sudo systemctl status sonarqube --no-pager
