#!/bin/bash

set -e

echo "========================================"
echo " SONARQUBE 9.9 LTS INSTALLATION STARTED "
echo "========================================"

# Update system
sudo apt update -y

# Install Java 17 + PostgreSQL + utilities
sudo apt install openjdk-17-jdk unzip wget postgresql postgresql-contrib -y
sudo postgresql-setup --initdb
# Start PostgreSQL
sudo systemctl enable postgresql
sudo systemctl start postgresql

# Create SonarQube DB and User
sudo -u postgres psql <<EOF
DROP DATABASE IF EXISTS sonarqube;
DROP USER IF EXISTS sonar;

CREATE USER sonar WITH ENCRYPTED PASSWORD 'sonar123';
CREATE DATABASE sonarqube OWNER sonar;

GRANT ALL PRIVILEGES ON DATABASE sonarqube TO sonar;
EOF

# Stop old SonarQube
sudo systemctl stop sonarqube || true
sudo pkill -f sonarqube || true
sudo pkill -f elasticsearch || true

# Remove old installation
sudo rm -rf /opt/sonarqube
sudo rm -f /etc/systemd/system/sonarqube.service

# Create sonar user
sudo useradd -r -m -U -d /opt/sonarqube -s /bin/bash sonar || true

# Download SonarQube 9.9 LTS
cd /tmp

wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.9.8.100196.zip

# Extract
unzip -o sonarqube-9.9.8.100196.zip

# Move files
sudo mv sonarqube-9.9.8.100196 /opt/sonarqube

# Permissions
sudo chown -R sonar:sonar /opt/sonarqube

# Configure database + low memory settings
sudo tee -a /opt/sonarqube/conf/sonar.properties > /dev/null <<EOF

sonar.jdbc.username=sonar
sonar.jdbc.password=sonar123
sonar.jdbc.url=jdbc:postgresql://localhost:5432/sonarqube

sonar.web.javaOpts=-Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError
sonar.ce.javaOpts=-Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError
sonar.search.javaOpts=-Xmx512m -Xms512m -XX:MaxDirectMemorySize=256m -XX:+HeapDumpOnOutOfMemoryError
EOF

# Linux kernel settings
echo "vm.max_map_count=524288" | sudo tee -a /etc/sysctl.conf
echo "fs.file-max=131072" | sudo tee -a /etc/sysctl.conf

echo "sonar - nofile 131072" | sudo tee -a /etc/security/limits.conf
echo "sonar - nproc 8192" | sudo tee -a /etc/security/limits.conf

sudo sysctl -p

# Create systemd service
sudo tee /etc/systemd/system/sonarqube.service > /dev/null <<EOF
[Unit]
Description=SonarQube service
After=syslog.target network.target

[Service]
Type=forking

ExecStart=/opt/sonarqube/bin/linux-x86-64/sonar.sh start
ExecStop=/opt/sonarqube/bin/linux-x86-64/sonar.sh stop

User=sonar
Group=sonar
Restart=always
LimitNOFILE=131072
LimitNPROC=8192
TimeoutStartSec=300

[Install]
WantedBy=multi-user.target
EOF

# Reload daemon
sudo systemctl daemon-reload

# Enable service
sudo systemctl enable sonarqube

# Start SonarQube
sudo systemctl start sonarqube

echo "========================================"
echo " WAIT 2-3 MINUTES FOR STARTUP "
echo "========================================"

sleep 120

# Status
sudo systemctl status sonarqube --no-pager

echo "========================================"
echo " SONARQUBE INSTALLATION COMPLETED "
echo "========================================"

echo ""
echo "Open Browser:"
echo "http://YOUR-EC2-PUBLIC-IP:9000"
echo ""

echo "Default Login"
echo "Username: admin"
echo "Password: admin"
