#!/bin/bash

set -e

echo "=============================="
echo " Updating System"
echo "=============================="

sudo apt update -y

echo "=============================="
echo " Installing Java 17"
echo "=============================="

sudo apt install openjdk-17-jdk wget unzip postgresql postgresql-contrib -y

echo "=============================="
echo " Starting PostgreSQL"
echo "=============================="

sudo systemctl enable postgresql
sudo systemctl start postgresql

echo "=============================="
echo " Creating SonarQube Database"
echo "=============================="

sudo -u postgres psql <<EOF
CREATE DATABASE sonarqube;
CREATE USER sonar WITH ENCRYPTED PASSWORD 'sonar123';
GRANT ALL PRIVILEGES ON DATABASE sonarqube TO sonar;
EOF

echo "=============================="
echo " Creating Sonar User"
echo "=============================="

sudo useradd -r -m -U -d /opt/sonarqube -s /bin/bash sonar || true

echo "=============================="
echo " Downloading SonarQube"
echo "=============================="

cd /tmp

wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-10.5.1.90531.zip

echo "=============================="
echo " Extracting SonarQube"
echo "=============================="

sudo unzip -o sonarqube-10.5.1.90531.zip -d /opt/

echo "=============================="
echo " Renaming Folder"
echo "=============================="

sudo rm -rf /opt/sonarqube

sudo mv /opt/sonarqube-10.5.1.90531 /opt/sonarqube

echo "=============================="
echo " Setting Permissions"
echo "=============================="

sudo chown -R sonar:sonar /opt/sonarqube

echo "=============================="
echo " Configuring SonarQube DB"
echo "=============================="

sudo tee -a /opt/sonarqube/conf/sonar.properties > /dev/null <<EOF

sonar.jdbc.username=sonar
sonar.jdbc.password=sonar123
sonar.jdbc.url=jdbc:postgresql://localhost:5432/sonarqube
EOF

echo "=============================="
echo " Configuring Linux Kernel"
echo "=============================="

sudo bash -c 'echo "vm.max_map_count=524288" >> /etc/sysctl.conf'
sudo bash -c 'echo "fs.file-max=131072" >> /etc/sysctl.conf'

sudo bash -c 'echo "sonar - nofile 131072" >> /etc/security/limits.conf'
sudo bash -c 'echo "sonar - nproc 8192" >> /etc/security/limits.conf'

sudo sysctl -p

echo "=============================="
echo " Creating SonarQube Service"
echo "=============================="

sudo tee /etc/systemd/system/sonarqube.service > /dev/null <<EOF
[Unit]
Description=SonarQube service
After=syslog.target network.target

[Service]
Type=forking

ExecStart=/opt/sonarqube/bin/linux-x86-64/sonar.sh start
ExecStop=/opt/sonarqube/bin/linux-x86-64/sonar.sh stop

User=sonar
Group=sonar
Restart=always
LimitNOFILE=131072
LimitNPROC=8192
TimeoutStartSec=300

[Install]
WantedBy=multi-user.target
EOF

echo "=============================="
echo " Reloading Systemd"
echo "=============================="

sudo systemctl daemon-reload

echo "=============================="
echo " Enabling SonarQube"
echo "=============================="

sudo systemctl enable sonarqube

echo "=============================="
echo " Starting SonarQube"
echo "=============================="

sudo systemctl start sonarqube

sleep 15

echo "=============================="
echo " SonarQube Status"
echo "=============================="

sudo systemctl status sonarqube --no-pager

echo "=============================="
echo " Installation Completed"
echo "=============================="

echo "Open Browser:"
echo "http://<YOUR-EC2-PUBLIC-IP>:9000"

echo ""
echo "Default Login"
echo "Username: admin"
echo "Password: admin"
sudo -u postgres psql

\c sonarqube

GRANT ALL PRIVILEGES ON DATABASE sonarqube TO sonar;

GRANT ALL ON SCHEMA public TO sonar;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO sonar;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO sonar;

ALTER SCHEMA public OWNER TO sonar;


\q




sudo systemctl restart sonarqube















